NopeForge/nope.gl

- configure.py
The daily builds are only kept for 14 days while the last build of each month is kept for two years.
Fixes the build on Windows.
> build: use the last FFmpeg build of last month on Windows

- CHANGELOG.md
- libnopegl/doc/libnopegl.md
- libnopegl/nodes.specs
- libnopegl/src/node_graphicconfig.c
The scissor parameter was implemented before the NGLI_PARAM_TYPE_IVEC* types were available. Switching to IVEC4 matches the internal scissor type.
> graphicconfig: change the scissor type from vec to ivec

- libnopegl/src/darray.c
- libnopegl/src/hmap.c
Fixes the following warnings on Windows:
- hmap.c(241,54): warning C4293: '<<': shift count negative or too big, undefined behavior
- darray.c(90,70): warning C4293: '<<': shift count negative or too big, undefined behavior
Fixes runtime errors on Windows due to regressions introduced by 609332e822b0c0afb766cef2dd975741c7ecd0c5 and
081ace38da7f29871906c7d44db351dd96a97a32.
> hmap, darray: fix invalid shifts

- libnopegl/src/backends/gl/pipeline_gl.c
The glUniform*v() functions use GLsizei for the count parameter.
> pipeline_gl: change uniform count variable from int to GLsizei

- libnopegl/scripts/gen-gl-wrappers.py
- libnopegl/src/backends/gl/gldefinitions_data.h
glInvalidateFramebuffer() is only present if GL_ARB_invalidate_subdata is supported, which is not the case on macOS.
Fixes a regression introduced by 9fb1c47a60375bc2fc343a763327601aed671fcb.
> gl: make glInvalidateFramebuffer() non-mandatory

- configure.py
We also change the source URL because the official distribution is down and doesn't seem it's going to come up again anytime soon.
The original source was preferred due to its more convenient tree layout and its inclusion of generated autotools files. But the fancy tree layout is handled fine by our build system, and we use meson instead of the autotools now, so these are not issues anymore.
> build: bump pkgconf from 1.9.4 to 1.9.5

- .github/workflows/ci_msvc.yml
The installers are GUI based meaning we might get control back before the install ends. This causes the vulkan DLL not to be available during configure, causing all kind of runtime linking issues.
See https://stackoverflow.com/questions/7908000/run-an-application-with-powershell-and-wait-until-it-is-finished for more information on the hack.
Debugged and analyzed with Matthieu Bouron.
> ci: wait for Vulkan installers to finish before proceeding further

- libnopegl/src/backends/gl/program_gl_utils.c
Fixes potential binding issues when using dynamic uniform buffers with OpenGL 3.0 contexts.
> program_gl_utils: also set block binding for dynamic uniform buffers

- .github/workflows/ci_linux.yml
- configure.py
Since a few days it seems the Github Actions CI resources got reduced. Starting from the HISTORY.md commit (87316921) the tests timings went from:
2023-08-03T12:44:59.7264391Z  41/984 ngl-tests:opengl+benchmark / fingerprint_with_compute       OK             23.93s
2023-08-03T12:49:13.3936743Z 700/984 ngl-tests:vulkan+benchmark / fingerprint_with_compute       OK             29.10s
To:
2023-08-08T09:36:27.2987889Z  42/984 ngl-tests:opengl+benchmark / fingerprint_with_compute       OK             35.31s
2023-08-08T09:42:22.5686176Z 699/984 ngl-tests:vulkan+benchmark / fingerprint_with_compute       OK             58.74s
The Vulkan tests are dangerously close to the 60 seconds timeout limit, which is sometimes reached. While there is certainly room for performance improvements in nopegl, …
> tests: increase the timeout multiplier again

- libnopegl/src/backends/gl/buffer_gl.c
- libnopegl/src/backends/gl/buffer_gl.h
- libnopegl/src/backends/vk/buffer_vk.c
- libnopegl/src/backends/vk/buffer_vk.h
- libnopegl/src/backends/vk/gpu_ctx_vk.c
- libnopegl/src/backends/vk/texture_vk.c
- libnopegl/src/buffer.c
- libnopegl/src/buffer.h
- libnopegl/src/distmap.c
- libnopegl/src/geometry.c
- libnopegl/src/gpu_ctx.h
- libnopegl/src/hud.c
- libnopegl/src/node_animatedbuffer.c
- libnopegl/src/node_block.c
- libnopegl/src/node_buffer.c
- libnopegl/src/node_renderother.c
- libnopegl/src/node_streamedbuffer.c
- libnopegl/src/node_text.c
- libnopegl/src/pipeline_compat.c
This makes the API more in line with the Vulkan API and our internal pipeline{,_compat}_update_buffer() functions.
> buffer: invert upload()/map() offset/size arguments order

- pynopegl-utils/pynopegl_utils/tests/cmp.py
Fix regression since cf5e73669ff3c5cb95376592908a4f758a105254.
> utils/cmp: fix typing annotation with Python 3.8

- pynopegl/setup.py
Fixes an issue where setuptools would not find the generated pynopegl *.py sources (as they were generated too late in the setup() procedure) leading to an incomplete installation.
This commit ensures that the relevant files are generated before setup() is run.
> pynopegl: generate source files before setup()

- .github/workflows/release_linux.yml
- .github/workflows/release_macos.yml
- CHANGELOG.md
github.ref_name was working when we were relying on tags events, but now we are relying on a workflow dependency, where it is undefined.
> ci/release: fix version reference

- pynopegl-utils/pynopegl_utils/qml/livectls.py
Fixes the following qml warning:
pynopegl-utils/pynopegl_utils/qml/viewer.qml:385:37: Unable to assign [undefined] to double
> utils/qml: set default live controls step to 1/100

- CHANGELOG.md
- libnopegl/src/hwconv.c
- libnopegl/src/pgcraft.h
The crash can be reproduced with ngl-player -d 0 <media> when using a hwaccel.
> Hwconv fixes

- libnopegl/src/backends/gl/glcontext.c
- libnopegl/src/backends/gl/glcontext_wgl.c
- libnopegl/src/backends/vk/vkcontext.c
- libnopegl/src/jni_utils.c
This does not solve any real issue as we are not manually interleaving data inside allocated memory region. When we do, like in the ngl_node allocation code, we properly pad each structs (pub, opts, priv)).
It is considered a better practice to use uintptr_t for platforms supporting it, to perform pointer arithmetic. Moreover it silences warnings when building libnopegl with -Wcast-align=strict.
> Ptr cast alignment

- CHANGELOG.md
- libnopegl/src/backends/gl/hwmap_mediacodec_gl.c
Fixes regression introduced by 7d297568172172e4047beb7d731a3a9dd91c41d5.
> hwmap_mediacodec_gl: fix NULL pointer dereference

- configure.py
- libnopegl/meson.build
According to upstream release notes, legacy HLSL and OGLCompiler libraries have been removed.
> build: bump glslang version to 14.0.0

- libnopegl/src/api.c
- libnopegl/src/backends/gl/gpu_ctx_gl.c
- libnopegl/src/backends/vk/gpu_ctx_vk.c
- libnopegl/src/gpu_ctx.c
- libnopegl/src/gpu_ctx.h
Depends on https://github.com/NopeForge/nope.gl/pull/229.
> gpu_ctx: remove viewport parameter from ngli_gpu_ctx_resize()

- configure.py
- patches/ffmpeg/0001-avcodec-add-av_jni_-get-set-_android_app_ctx-helper.patch
- patches/ffmpeg/0002-avformat-add-Android-content-resolver-protocol-suppo.patch
- patches/ffmpeg/0003-avcodec-jni-use-size_t-to-store-structure-offsets.patch
- patches/ffmpeg/0004-avcodec-jni-remove-unnecessary-NULL-checks-before-ca.patch
- patches/ffmpeg/0005-avcodec-mediacodec_wrapper-use-an-OFFSET-macro-where.patch
- patches/ffmpeg/0006-avcodec-mediacodec_wrapper-remove-unnecessary-NULL-c.patch
See https://ffmpeg.org/pipermail/ffmpeg-devel/2024-February/321424.html.
> build: add android content uri support to FFmpeg

- ngl-tools/player.c
This parameter doesn't exist since 7b6b04aa6893ae02a5bd3076eaffea804a8c07dd.
> tools/player: do not try to change Text.aspect_ratio

- libnopegl/src/node_hblur.c
pass2_rtt_ctx is already allocated earlier in the function.
Fixes CID 1584829.
> hblur: remove superfluous allocation

- .github/workflows/ci_android.yml
- .github/workflows/ci_coverage.yml
- .github/workflows/ci_coverity.yml
- .github/workflows/ci_linux.yml
- .github/workflows/doc.yml
- .github/workflows/release_linux.yml
- doc/usr/howto/installation.md
- libnopegl/meson.build
- libnopegl/src/backends/vk/glslang_utils.c
Depends on https://github.com/NopeForge/nope.gl/pull/258 and Ubuntu 24.04 CI support (public beta is planned for mid may).
> ci: bump Ubuntu version from 22.04 to 24.04

- configure.py
See https://github.com/KhronosGroup/glslang/releases/tag/14.2.0. Mostly bug fixes, which are always welcome :).
> build: bump glslang version to 14.2.0

- libnopegl/src/glsl/helper_noise.glsl
To reproduce the problem, use for example uv*2-1 instead of uv in source_noise.frag, then check noise_{perlin,blocky} scenes from tests/noise.py.
The fix makes sure we stay in the signed world as long as possible, and only switch to unsigned for hashing.
The noise 1D implementation is currently left unchanged as the time can't be negative, but it might make sense to change it as well there eventually.
> noise: fix 3d noise with negative coordinates

- CHANGELOG.md
- libnopegl/meson.build
- libnopegl/meson_options.txt
- libnopegl/src/utils/utils.h
Now docstrings are not included in the library anymore (5.1M to 5.0M on a release build) and only present for the gen_specs executable.
The comment in the meson build is removed because we won't be able to share the object anymore since they are built with different options.
> build: simplify small build logic

- configure.py
See:
- https://github.com/KhronosGroup/glslang/releases/tag/15.4.0
- https://github.com/KhronosGroup/glslang/commit/32f71d72a2643df675684e1795e987ac26e600df
> build: bump glslang version from 15.3.0 to 15.4.0
