NopeForge/nope.gl

- libnopegl/meson.build
- libnopegl/src/backends/vk/gpu_ctx_vk.c
- libnopegl/src/bstr.c
- libnopegl/src/darray.c
- libnopegl/src/darray.h
- libnopegl/src/deserialize.c
- libnopegl/src/hmap.c
- libnopegl/src/memory.c
- libnopegl/src/memory.h
- libnopegl/src/params.c
Far from being enough, but that's a start.
> Overflow checks

- libnopegl/src/backends/gl/buffer_gl.c
- libnopegl/src/backends/gl/buffer_gl.h
- libnopegl/src/backends/gl/glincludes.h
- libnopegl/src/backends/gl/pipeline_gl.c
- libnopegl/src/backends/gl/pipeline_gl.h
- libnopegl/src/backends/gl/texture_gl.c
- libnopegl/src/backends/gl/texture_gl.h
- libnopegl/src/pgcraft.c
Required by https://github.com/nope-project/nope.gl/pull/3.
> pipeline: fix write after read hazards

- libnopegl/src/backends/gl/egl.h
- libnopegl/src/backends/gl/feature_gl.h
- libnopegl/src/backends/gl/glcontext.c
- libnopegl/src/backends/gl/glcontext.h
- libnopegl/src/backends/gl/glcontext_egl.c
- libnopegl/src/backends/gl/pipeline_gl.c
Fixes https://github.com/nope-project/nope.gl/pull/3 with radeonsi.
> Workaround a synchronization issue with radeonsi

- libnopegl/src/backends/gl/glstate.c
- libnopegl/src/backends/gl/glstate.h
- libnopegl/src/backends/gl/gpu_ctx_gl.c
- libnopegl/src/backends/gl/pipeline_gl.c
- libnopegl/src/backends/vk/gpu_ctx_vk.c
- libnopegl/src/backends/vk/pipeline_vk.c
- libnopegl/src/gpu_ctx.c
- libnopegl/src/gpu_ctx.h
- libnopegl/src/hud.c
- libnopegl/src/hwconv.c
- libnopegl/src/node_graphicconfig.c
- libnopegl/src/node_renderother.c
- libnopegl/src/node_rtt.c
- libnopegl/src/pass.c
Depends on https://github.com/nope-project/nope.gl/pull/64.
> Viewport scissor structures

- libnopegl/src/glsl/text_chars.frag
- libnopegl/src/glsl/text_chars.vert
- libnopegl/src/node_text.c
- libnopegl/src/text.c
- libnopegl/src/text.h
This reduces the number of attributes for which the limit can be quite small on some backends/platforms.
> text: pack color and opacity in a vec4

- .github/meson-ios-x86_64.ini
- .github/workflows/ci_coverage.yml
- .github/workflows/ci_linux.yml
This was forgotten in 31b8d690aeec6555a07a560146f03a7df988dc24.
> ci/coverage: add timeout multiplier

- .github/workflows/ci_linux.yml
- .github/workflows/doc.yml
- CHANGELOG.md
- doc/_ext/nope/__init__.py
- doc/_ext/nope/blending/fade.py
- doc/_ext/nope/blending/overlay.py
- doc/_ext/nope/nope.css
- doc/_ext/nope/nope.js
- doc/_ext/nope/renders/gradient.py
- doc/_ext/nope/renders/image.py
- doc/_ext/nope/renders/shadertoy.py
- doc/_ext/nope/renders/video.py
- doc/_ext/nope/shapes/circle.py
- doc/_ext/nope/shapes/geometry.py
- doc/_ext/nope/shapes/quad.py
- doc/_ext/nope/shapes/triangle.py
- doc/_ext/nope/timeranges/shapes.py
- doc/_ext/nope/transforms/animated_rotate.py
- doc/_ext/nope/transforms/animated_scale.py
- doc/_ext/nope/transforms/animated_translate.py
- doc/_ext/nope/transforms/rotate.py
- doc/conf.py
- doc/requirements.txt
- doc/usr/howto/blending.md
- doc/usr/howto/index.md
- doc/usr/howto/renders.md
- doc/usr/howto/shapes.md
- doc/usr/howto/timeranges.md
- doc/usr/howto/transforms.md
Depends on https://github.com/NopeFoundry/nope.gl/pull/138
> Documentation: part 3 (code snippet with render + graph)

- pynopegl-utils/pynopegl_utils/qml/viewer.qml
- pynopegl-utils/pynopegl_utils/viewer/__init__.py
Submitted as a draft because content might have to be refined.
> Viewer About popup

- configure.py
- pynopegl-utils/pynopegl_utils/export.py
> utils/export: add MP4 / AV1 4:2:0 profile

- .github/workflows/release.yml
- scripts/release-changelog.py
Tested on my github: https://github.com/ubitux/nope.gl/releases/
> ci: add and use release changelog script

- .github/workflows/doc.yml
- doc/index.md
Note that the redirecting message will only be visible starting next release.
> doc: provide both main and latest stable versions of the documentation

- libnopegl/src/backends/vk/pipeline_vk.c
> pipeline_vk: fix potential NULL pointer dereference

- ngl-tools/ngl-desktop.c
Regression since e30dbd400eed593e29c27cd73a426a3f27ffc024.
> tools/desktop: fix backend probing

- .github/workflows/ci_android.yml
- .github/workflows/ci_ios.yml
- configure.py
> build/ci: bump nope.media version to v11.1.1

- libnopegl/src/node_fgblur.c
> fgblur: fix potential memory leak

- pynopegl-utils/pynopegl_utils/qml/ngl_widget.py
Forgotten in 57bdedde29f6d7e2e8e620fb9ba73a44287da1e5
> utils/qml: fix forgotten resize() adjustment

- CHANGELOG.md
- libnopegl/nodes.specs
- libnopegl/src/internal.h
- libnopegl/src/node_fontface.c
- libnopegl/src/text_external.c
Tested with the Iosevka TTC font
> fontface: add index parameter

- pynopegl-utils/pynopegl_utils/qml/Player.qml
Fixes a regression introduced by adcef0dedb15e063730ded88e89f1c12632d5e07.
> utils/player: fix ngl widget size

- .github/workflows/doc.yml
> ci/doc: bump upload-pages-artifact and deploy-pages versions

- libnopegl/src/api.c
- libnopegl/src/backends/vk/hwmap_mediacodec_vk.c
- libnopegl/src/blending.c
- libnopegl/src/blending.h
- libnopegl/src/hwmap_common.c
- libnopegl/src/node_circle.c
- libnopegl/src/node_colorstats.c
- libnopegl/src/node_eval.c
- libnopegl/src/node_rotate.c
- libnopegl/src/pass.c
- libnopegl/src/pass.h
- libnopegl/src/pipeline_compat.c
- libnopegl/src/utils.h
Misc fixes before the GPU refactoring PR.
> Misc fixes

- libnopegl/src/ngpu/bindgroup.h
- libnopegl/src/ngpu/opengl/pipeline_gl.c
- libnopegl/src/ngpu/opengl/program_gl_utils.c
- libnopegl/src/ngpu/pgcraft.c
- libnopegl/src/ngpu/pgcraft.h
- libnopegl/src/ngpu/pipeline.h
- libnopegl/src/pass.c
Depends on https://github.com/NopeForge/nope.gl/pull/290.
> Change location binding rate type

- CHANGELOG.md
- libnopegl/nodes.specs
- libnopegl/src/node_buffer.c
- libnopegl/src/node_circle.c
- libnopegl/src/node_program.c
- libnopegl/src/node_program.h
- libnopegl/src/node_streamedbuffer.c
Fixes -Wsign-conversion warnings.
> node_{circle,buffer,streamedbuffer}: make count unsigned

- CHANGELOG.md
- pynopegl-utils/pynopegl_utils/export.py
- pynopegl-utils/setup.py
Useful for testing purpose, typically running it on a script from the tests directory.
> utils: add ngl-export
